"""Clients model updated

Revision ID: 5fefaeb19a30
Revises: f44517750bbb
Create Date: 2026-01-20 20:06:53.038533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fefaeb19a30'
down_revision: Union[str, Sequence[str], None] = 'f44517750bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clients_phone_key'), 'clients', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('clients_phone_key'), 'clients', ['phone'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
