"""provider id add to appointment model

Revision ID: ed8d6ab2d12e
Revises: 28eddb73be5a
Create Date: 2025-08-30 12:22:05.433233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed8d6ab2d12e'
down_revision: Union[str, Sequence[str], None] = '28eddb73be5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('provider_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'users', ['provider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'provider_id')
    # ### end Alembic commands ###
