"""business name

Revision ID: f44517750bbb
Revises: ed8d6ab2d12e
Create Date: 2026-01-19 19:03:04.392784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44517750bbb'
down_revision: Union[str, Sequence[str], None] = 'ed8d6ab2d12e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('business_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'business_name')
    # ### end Alembic commands ###
