name: CI

on:
  push: 
    branches: [main]
  pull_request: 
    branches: [main]
    
jobs: 
  backend-tests:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: 
          python-version: "3.13"

      - name: Install Poetry
        run: pip install poetry

      - name: Install Backend Dependencies
        run: poetry install --no-root

      - name: Run Backend Tests
        run: poetry run pytest

  fronend-tests:
    runs-on: ubuntu-latest

    defaults: 
      run:  
        working-directory: frontend
      
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: 
          node-version: "22"

      - name: Install frontend dependencies 
        run: npm ci

      - name: Run lint 
        run: npm run lint
        
      - name: build forntend
        run: npm run build